spring.application.name=similar-products
server.port=5000
existing-apis.base-url=http://localhost:3001
management.endpoints.web.exposure.include=health,metrics
existing-apis.request-timeout=2s
spring.http.clients.connect-timeout=1s
spring.http.clients.read-timeout=60s
product-cache.ttl=1m
product-cache.error-ttl=1s
product-cache.maximum-size=10000